[project]
name = "afterglow-kolla-operator"
version = "0.1.0"
description = "Afterglow Kolla-Ansible operator environment specification"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kolla-ansible @ git+https://opendev.org/openstack/kolla-ansible@34daacfbf2d5987f543787f57535b2bebe7dee19",
    "drover-kolla @ https://github.com/openstack-afterglow/drover/releases/download/v0.2.19/drover_kolla-0.2.19-py3-none-any.whl#sha256=9d11fdc3a07240a3d613ba878102668b0f9b5cf35b5bd3f3ce6e033426a12392",
    "lumen-kolla @ https://github.com/openstack-afterglow/lumen/releases/download/v0.2.0/lumen_kolla-0.2.0-py3-none-any.whl#sha256=d55e2b0ace06d232452f9dd2892a88912755e9d00e99de0e59d6738c5a3b2474",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
