[project]
name = "afterglow-kolla-operator"
version = "0.1.0"
description = "Afterglow Kolla-Ansible operator environment specification"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kolla-ansible",
    "drover",
    "lumen",
    "waygate",
    "palimpsest-local",
]

[tool.uv.sources]
kolla-ansible = { git = "https://opendev.org/openstack/kolla-ansible.git", rev = "34daacfbf2d5987f543787f57535b2bebe7dee19" }
drover = { git = "https://github.com/openstack-afterglow/drover.git", rev = "3d21f785f4255d8c82d1772453eb7b64847f518b" }
lumen = { git = "https://github.com/openstack-afterglow/lumen.git", rev = "3ab1f2ffe6565106453325c2a2f187cc6c11c0cf" }
waygate = { git = "https://github.com/openstack-afterglow/waygate.git", rev = "9933deb97fcacfea70305b5b8eb5c9b6d32b33c1" }
palimpsest-local = { git = "https://github.com/openstack-afterglow/palimpsest.git", rev = "c82bc0f494077779452c21e98714bec8b51cafa2" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
